### ISSUE TITLE
Optional value, not really optional

### ISSUE THREAD

**Issue by luispadron** [muenzpraeger/salesforce-einstein-vision-swift#8]
So I am passing `nil` to the `PredictionService.predict` method, I saw that `sampleId` is an optional value. Passing `nil` to this parameter causes a Swift error because of force unwrapping an optional value.

Here is an example

```swift
predictionService.predictUrl(modelId: "GeneralImageClassifier",
                                                  url: imageUrl, sampleId: nil)
        { (result) in
            debugPrint(result ?? "error")
        }
```

Inside PredictionService.swift file:

```swift
///   - sampleId: Optional. A string that gets returned as an association with the predicted image.
. . .
try multiPart.build(modelId: modelId, data: filePath, sampleId: sampleId!, type: SourceType.file)
```
Due to the force unwrapping Swift will throw `fatal error: unexpectedly found nil while unwrapping an Optional value`

**Comment by luispadron** [comment]
Thanks for updating so quickly, however the pod has not been updated in the cocoapods trunk.
Still on version 1.3.1.

```bash
[!] Unable to satisfy the following requirements:

- `SalesforceEinsteinVision (~> 1.3.2)` required by `Podfile`
```

**Comment by muenzpraeger** [comment]
Fixed (again ;-))
